name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear el código
        uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'

      - name: Instalar dependencias
        run: npm install

      - name: Establecer permisos para node_modules
        run: chmod -R 777 ./node_modules 

      - name: Ejecutar pruebas
        run: npm test
